################################################################################
# File name: vivado_wc_pre.tcl
# Purpose  : This is an internal file that is auto generated by Vivado to source
#            the user tcl file.
################################################################################
open_project "E:/Project/RO_TRNG/fpga/RO_TRNG.xpr"
set rc [catch {
  source -notrace "E:/Project/RO_TRNG/sim/set_timestamp.tcl"
} result]
if {$rc} {
  puts "$result"
  puts "ERROR: Script failed:\"E:/Project/RO_TRNG/sim/set_timestamp.tcl\""
}
close_project
