set_property SRC_FILE_INFO {cfile:E:/Project/MLDSA/RO_TRNG/fpga1/xc7z020clg400/xc7z020clg400.srcs/constrs_1/imports/new/timing.xdc rfile:../../../xc7z020clg400.srcs/constrs_1/imports/new/timing.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:E:/Project/MLDSA/RO_TRNG/fpga1/xc7z020clg400/xc7z020clg400.srcs/constrs_1/new/pin.xdc rfile:../../../xc7z020clg400.srcs/constrs_1/new/pin.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -hierarchical -filter {NAME =~ *u_entropy_source/RO_SAMPLE_LOOP[0].u_LUT6_not1/in0[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -hierarchical -filter {NAME =~ *u_entropy_source/RO_NUM_LOOP[*].RO_AND.u_LUT6_and2_1/in0[0]}]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N16 [get_ports por_n_i]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports UART_TX_o]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports sys_clk]
