# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Project/MLDSA/RO_TRNG/fpga1/xc7z020clg400/xc7z020clg400.srcs/sources_1/ip/proc_sys_reset_0/proc_sys_reset_0.xci
# IP: The module: 'proc_sys_reset_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/MLDSA/RO_TRNG/fpga1/xc7z020clg400/xc7z020clg400.gen/sources_1/ip/proc_sys_reset_0/proc_sys_reset_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_sys_reset_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/MLDSA/RO_TRNG/fpga1/xc7z020clg400/xc7z020clg400.gen/sources_1/ip/proc_sys_reset_0/proc_sys_reset_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_sys_reset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/MLDSA/RO_TRNG/fpga1/xc7z020clg400/xc7z020clg400.gen/sources_1/ip/proc_sys_reset_0/proc_sys_reset_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_sys_reset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Project/MLDSA/RO_TRNG/fpga1/xc7z020clg400/xc7z020clg400.srcs/sources_1/ip/proc_sys_reset_0/proc_sys_reset_0.xci
# IP: The module: 'proc_sys_reset_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/MLDSA/RO_TRNG/fpga1/xc7z020clg400/xc7z020clg400.gen/sources_1/ip/proc_sys_reset_0/proc_sys_reset_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_sys_reset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/MLDSA/RO_TRNG/fpga1/xc7z020clg400/xc7z020clg400.gen/sources_1/ip/proc_sys_reset_0/proc_sys_reset_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_sys_reset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/MLDSA/RO_TRNG/fpga1/xc7z020clg400/xc7z020clg400.gen/sources_1/ip/proc_sys_reset_0/proc_sys_reset_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'proc_sys_reset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
