set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -hierarchical -filter {NAME =~ *u_entropy_source/RO_SAMPLE_LOOP[0].u_LUT6_not1/in0[0]}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -hierarchical -filter {NAME =~ *u_entropy_source/RO_NUM_LOOP[*].RO_AND.u_LUT6_and2_1/in0[0]}]

set_disable_timing -from I0 -to O [get_cells -hierarchical -filter {NAME =~ *u_entropy_source/RO_SAMPLE_NAND.u_LUT6_nand2_1/u_LUT6}]
set_disable_timing -from I1 -to O [get_cells -hierarchical -filter {NAME =~ *u_entropy_source/RO_SAMPLE_NAND.u_LUT6_nand2_1/u_LUT6}]

create_clock -name clk_sample0 -period 5.000 [get_pins -hierarchical -filter {NAME =~ *u_entropy_source/RO_SAMPLE_NAND.u_LUT6_nand2_1/u_LUT6/O}]
create_clock -name clk_sample1 -period 5.000 [get_pins -hierarchical -filter {NAME =~ *u_entropy_source/RO_SAMPLE_LOOP[0].u_LUT6_not1/u_LUT6/O}]
create_clock -name clk_sample2 -period 5.000 [get_pins -hierarchical -filter {NAME =~ *u_entropy_source/RO_SAMPLE_LOOP[1].u_LUT6_not1/u_LUT6/O}]
create_clock -name clk_sample3 -period 5.000 [get_pins -hierarchical -filter {NAME =~ *u_entropy_source/RO_SAMPLE_LOOP[2].u_LUT6_not1/u_LUT6/O}]
create_clock -name clk_sample4 -period 5.000 [get_pins -hierarchical -filter {NAME =~ *u_entropy_source/RO_SAMPLE_LOOP[3].u_LUT6_not1/u_LUT6/O}]
create_clock -name clk_sample5 -period 5.000 [get_pins -hierarchical -filter {NAME =~ *u_entropy_source/RO_SAMPLE_LOOP[4].u_LUT6_not1/u_LUT6/O}]
create_clock -name clk_sample6 -period 5.000 [get_pins -hierarchical -filter {NAME =~ *u_entropy_source/RO_SAMPLE_LOOP[5].u_LUT6_not1/u_LUT6/O}]
create_clock -name clk_sample7 -period 5.000 [get_pins -hierarchical -filter {NAME =~ *u_entropy_source/RO_SAMPLE_LOOP[6].u_LUT6_not1/u_LUT6/O}]
create_clock -name clk_sample8 -period 5.000 [get_pins -hierarchical -filter {NAME =~ *u_entropy_source/RO_SAMPLE_LOOP[7].u_LUT6_not1/u_LUT6/O}]

set_false_path -from [get_clocks clk_sample0]
set_false_path -from [get_clocks clk_sample1]
set_false_path -from [get_clocks clk_sample2]
set_false_path -from [get_clocks clk_sample3]
set_false_path -from [get_clocks clk_sample4]
set_false_path -from [get_clocks clk_sample5]
set_false_path -from [get_clocks clk_sample6]
set_false_path -from [get_clocks clk_sample7]
set_false_path -from [get_clocks clk_sample8]